"""empty message

Revision ID: 7cbb3096f237
Revises: 
Create Date: 2023-11-26 04:10:32.500226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cbb3096f237'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('telephon_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pay_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pay_method_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('product_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('week_days',
    sa.Column('week_day', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('week_day')
    )
    op.create_table('weeks',
    sa.Column('week', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('week')
    )
    op.create_table('period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week', sa.String(), nullable=True),
    sa.Column('week_day', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['week'], ['weeks.week'], ),
    sa.ForeignKeyConstraint(['week_day'], ['week_days.week_day'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('contract_number', sa.Integer(), nullable=True),
    sa.Column('contract_situationm', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['period.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('pay_method_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['pay_method_id'], ['pay_method.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pays')
    op.drop_table('contracts')
    op.drop_table('period')
    op.drop_table('weeks')
    op.drop_table('week_days')
    op.drop_table('products')
    op.drop_table('pay_method')
    op.drop_table('customers')
    # ### end Alembic commands ###
